# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faceswap.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(1090, 727)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icon_studio_phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        self.VideoFileBtn = QtWidgets.QPushButton(Dialog)
        self.VideoFileBtn.setGeometry(QtCore.QRect(310, 40, 111, 21))
        self.VideoFileBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.VideoFileBtn.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/ee6c_64x.contrast-black.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.VideoFileBtn.setIcon(icon1)
        self.VideoFileBtn.setDefault(False)
        self.VideoFileBtn.setFlat(False)
        self.VideoFileBtn.setObjectName("VideoFileBtn")
        self.VideoFileNameLE = QtWidgets.QLineEdit(Dialog)
        self.VideoFileNameLE.setGeometry(QtCore.QRect(40, 40, 241, 21))
        self.VideoFileNameLE.setFocusPolicy(QtCore.Qt.NoFocus)
        self.VideoFileNameLE.setReadOnly(True)
        self.VideoFileNameLE.setObjectName("VideoFileNameLE")
        self.FaceFileBtn = QtWidgets.QPushButton(Dialog)
        self.FaceFileBtn.setGeometry(QtCore.QRect(310, 90, 111, 21))
        self.FaceFileBtn.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/icons8-unsplash-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FaceFileBtn.setIcon(icon2)
        self.FaceFileBtn.setObjectName("FaceFileBtn")
        self.FaceImageFileNameLE = QtWidgets.QLineEdit(Dialog)
        self.FaceImageFileNameLE.setGeometry(QtCore.QRect(40, 90, 241, 21))
        self.FaceImageFileNameLE.setFocusPolicy(QtCore.Qt.NoFocus)
        self.FaceImageFileNameLE.setReadOnly(True)
        self.FaceImageFileNameLE.setObjectName("FaceImageFileNameLE")
        self.FaceImageLB = QtWidgets.QLabel(Dialog)
        self.FaceImageLB.setGeometry(QtCore.QRect(500, 20, 151, 151))
        self.FaceImageLB.setFrameShape(QtWidgets.QFrame.Box)
        self.FaceImageLB.setLineWidth(1)
        self.FaceImageLB.setText("")
        self.FaceImageLB.setObjectName("FaceImageLB")
        self.RunBtn = QtWidgets.QPushButton(Dialog)
        self.RunBtn.setEnabled(True)
        self.RunBtn.setGeometry(QtCore.QRect(740, 110, 96, 48))
        self.RunBtn.setStyleSheet("#RunBtn {\n"
                                  "    background-color: #2196f3;\n"
                                  "    min-width: 96px;\n"
                                  "    max-width: 96px;\n"
                                  "    min-height: 48px;\n"
                                  "    max-height: 48px;\n"
                                  "    border-radius: 12px; \n"
                                  "    font-size: 24px;\n"
                                  "    color: #ff0000;\n"
                                  "}\n"
                                  "#RunBtn:hover {\n"
                                  "    background-color: #64b5f6;\n"
                                  "}\n"
                                  "#RunBtn:pressed {\n"
                                  "    background-color: #bbdefb;\n"
                                  "}")
        self.RunBtn.setObjectName("RunBtn")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(30, 690, 1061, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 180, 1021, 481))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.OriginVideoLB = QtWidgets.QLabel(self.groupBox)
        self.OriginVideoLB.setGeometry(QtCore.QRect(30, 40, 471, 331))
        self.OriginVideoLB.setFrameShape(QtWidgets.QFrame.Box)
        self.OriginVideoLB.setText("")
        self.OriginVideoLB.setObjectName("OriginVideoLB")
        self.ProceedVideoLB = QtWidgets.QLabel(self.groupBox)
        self.ProceedVideoLB.setGeometry(QtCore.QRect(520, 40, 471, 331))
        self.ProceedVideoLB.setFrameShape(QtWidgets.QFrame.Box)
        self.ProceedVideoLB.setText("")
        self.ProceedVideoLB.setObjectName("ProceedVideoLB")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(210, 10, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(730, 10, 121, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 390, 951, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.startButton = QtWidgets.QPushButton(self.groupBox)
        self.startButton.setEnabled(False)
        self.startButton.setGeometry(QtCore.QRect(90, 430, 171, 23))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/icons8-start-40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon3)
        self.startButton.setObjectName("startButton")
        self.pauseButton = QtWidgets.QPushButton(self.groupBox)
        self.pauseButton.setGeometry(QtCore.QRect(770, 430, 171, 23))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/icons8-pause-button-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon4)
        self.pauseButton.setObjectName("pauseButton")
        self.compareButton = QtWidgets.QPushButton(self.groupBox)
        self.compareButton.setEnabled(False)
        self.compareButton.setGeometry(QtCore.QRect(430, 430, 151, 23))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/wmp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.compareButton.setIcon(icon5)
        self.compareButton.setObjectName("compareButton")
        self.statusbar = QtWidgets.QLabel(Dialog)
        self.statusbar.setGeometry(QtCore.QRect(30, 842, 451, 21))
        self.statusbar.setText("")
        self.statusbar.setObjectName("statusbar")
        self.ExitBtn = QtWidgets.QPushButton(Dialog)
        self.ExitBtn.setGeometry(QtCore.QRect(910, 110, 96, 48))
        self.ExitBtn.setStyleSheet("#ExitBtn {\n"
                                   "    background-color: #2196f3;\n"
                                   "    min-width: 96px;\n"
                                   "    max-width: 96px;\n"
                                   "    min-height: 48px;\n"
                                   "    max-height:48px;\n"
                                   "    border-radius:12px; \n"
                                   "    font-size: 24px;\n"
                                   "    color: #00ff00;\n"
                                   "}\n"
                                   "#ExitBtn:hover {\n"
                                   "    background-color: #64b5f6;\n"
                                   "}\n"
                                   "#ExitBtn:pressed {\n"
                                   "    background-color: #bbdefb;\n"
                                   "}")
        self.ExitBtn.setObjectName("ExitBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Face Swap"))
        self.VideoFileBtn.setText(_translate("Dialog", "Open Video"))
        self.FaceFileBtn.setText(_translate("Dialog", "Open Face"))
        self.RunBtn.setText(_translate("Dialog", "Run"))
        self.label.setText(_translate("Dialog", "Original Video"))
        self.label_2.setText(_translate("Dialog", "Transformed Video"))
        self.startButton.setText(_translate("Dialog", "Start"))
        self.pauseButton.setText(_translate("Dialog", "Pause"))
        self.compareButton.setText(_translate("Dialog", "Compare"))
        self.ExitBtn.setText(_translate("Dialog", "Exit"))
